### ISSUE TITLE
Fix "bad command" error when users begin a message with a bad ellipsis

### ISSUE THREAD

**Issue by 2mac** [buttbot-irc/buttbot#1]
buttbot already ignores the command "..." for obvious reasons, but humans are humans and don't always strictly use 3 dots or remember to put a space after the ellipsis. buttbot should be more lenient about this.

I propose we change buttbot so that if a "command" begins with "..", then the whole line is considered a message and not a command. As far as I know, there are not any real commands that begin with "..", so this should be a simple fix for all such issues.

**Comment by agjmills** [comment]
This is fixed with the .config supybot.reply.whennotcommand false configuration setting
