### ISSUE TITLE
Update .source command

### ISSUE THREAD

**Issue by OtakuSenpai** [buttbot-irc/buttbot#3]
<Nawab> .source
<buttbot> Nawab: My source is at https://github.com/ProgVal/Limnoria

Which is not the correct link.
Pls fix

**Comment by agjmills** [comment]
The source of Limnoria is at https://github.com/ProgVal/Limnoria therefore the `.source` command is correct

I will happily add another command which will direct users to this repository if they want to make a feature request, or report a bug, but I don't want to remove the original link as I appreciate the developers times in developing Limnoria, therefore I feel they deserve some attribution.

If you would like a command to direct users to this repository, please let me know what you would like the command to be, and I'll implement it when I have some free time.

**Comment by OtakuSenpai** [comment]
Maybe you could do something like this:
buttbot> OtakuSenpai: My source is at https://github.com/buttbot-irc/buttbot , and I'm a fork of Limmoria hosted at https://github.com/ProgVal/Limnoria

**Comment by agjmills** [comment]
What value does this add?

**Comment by agjmills** [comment]
Added with V2 release
